# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f99976cee06f9c12da3bc9ec0f38680d7ad2b80786433dcedfb1cc5c1d2b5d004937b3d2b13fa6a125e93ea77dbcd468540b9bac81c7fc7796a5bad58456bc35

test:
  secret_key_base: be05b68617a1f1f051180bed460f6de7b298934d904025dbbb53d376fe84285fdc2a8d00f82a1a955d076d113c9fee51dd3290aa8f5a7ebf84a038191c2c22f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
